name: Workflow to build Docker image
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      node_env:
        required: false
        type: string
        default: "production"
      push:
        required: false
        type: boolean
        default: true
      docker_context:
        description: "the path where docker build execute."
        required: false
        default: "./"
        type: string
      runner:
        ## ['cn', 'us', 'cn1', 'cn2', 'cn3', 'us1', 'us2', 'us3']
        type: string
        default: "cn"
        required: false
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      REGISTRY:
        required: true
      NPM_TOKEN:
        required: false
jobs:
  build:
    name: build docker image
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      # Scan repo for secrets
      - name: Run scanner for the repository
        run: /usr/local/bin/whispers ${{ github.workspace }} > /tmp/scan_output.json

      # Upload Artifacts
      - name: Upload the scan output
        uses: actions/upload-artifact@v2
        with:
          name: scan_results
          path: /tmp/scan_output.json
          retention-days: 2

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.REGISTRY }}/${{ inputs.project }}/${{ inputs.component }}
          tags: |
            type=edge
            type=ref,event=branch
            type=ref,event=tag

      - name: Login to PrivateRegistry
        # https://github.com/actions/runner/issues/1483
        if: ${{ inputs.push == 'true' }}
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.docker_context }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            OMNI_COMPONENT=${{ inputs.component }}
            NODE_ENV=${{ inputs.node_env }}
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            OMNI_COMPONENT_COMMIT=${{ github.sha }}
            OMNI_COMPONENT_VERSION=${{ github.ref }}
