name: Workflow to build Docker image
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        # not required now
        required: false
        type: string
      node_env:
        required: false
        type: string
        default: "production"
      push:
        required: false
        type: boolean
        default: true
      docker_context:
        description: "the path where docker build execute."
        required: false
        default: "./"
        type: string
      docker_file:
        description: "the Dockerfile to build"
        required: false
        default: "./Dockerfile"
        type: string
      runner:
        ## ['cn', 'us', 'cn1', 'cn2', 'cn3', 'us1', 'us2', 'us3']
        type: string
        default: "cn"
        required: false
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      REGISTRY:
        required: true
      NPM_TOKEN:
        required: false
      MINIO_CN_ACCESS_KEY_ID:
        required: true
      MINIO_CN_SECRET_ACCESS_KEY:
        required: true
jobs:
  build:
    name: build docker image
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 20
    env:
      COMPONENT_NAME: "${{ inputs.component || github.event.repository.name }}"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.REGISTRY }}/${{ inputs.project }}/${{ env.COMPONENT_NAME }}
          tags: |
            type=edge
            type=ref,event=branch
            type=ref,event=tag

      - name: Login to PrivateRegistry
        # https://github.com/actions/runner/issues/1483
        if: ${{ inputs.push }}
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD}}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.docker_context }}
          file: ${{ inputs.docker_file }}
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            OMNI_COMPONENT=${{ env.COMPONENT_NAME }}
            NODE_ENV=${{ inputs.node_env }}
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            OMNI_COMPONENT_COMMIT=${{ github.sha }}
            OMNI_COMPONENT_VERSION=${{ steps.meta.outputs.version }}
      
      - name: Set docker image tar version
        id: setimgver
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=IMAGE_TAR_VER::$calculatedSha"
          
      - name: save docker image to tar file
        run: docker save --output ${{ inputs.project }}-${{ env.COMPONENT_NAME }}-${{ steps.setimgver.outputs.IMAGE_TAR_VER }}.tar ${{ steps.meta.outputs.tags }}

      - name: upload docker image to private minio storage
        run: |   
          export AWS_ACCESS_KEY_ID=${{ secrets.MINIO_CN_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.MINIO_CN_SECRET_ACCESS_KEY }}
          aws --endpoint-url http://10.10.1.30:9000 s3 cp  "${{ inputs.project }}-${{ env.COMPONENT_NAME }}-${{ steps.setimgver.outputs.IMAGE_TAR_VER }}.tar" s3://docker-img-artifacts 

      - name: push image
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.docker_context }}
          file: ${{ inputs.docker_file }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            OMNI_COMPONENT=${{ env.COMPONENT_NAME }}
            NODE_ENV=${{ inputs.node_env }}
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            OMNI_COMPONENT_COMMIT=${{ github.sha }}
            OMNI_COMPONENT_VERSION=${{ steps.meta.outputs.version }}

    outputs:
      imageTag: ${{ steps.meta.outputs.tags }}
  

