name: Workflow to post status msg in Slack channel
on:
  workflow_call:
    inputs:
      status:
        #['success', 'failure', 'cancelled', 'skipped']
        type: string
        required: false
      slack_channel_id:
        type: string
        required: true
      msg:
        type: string
        required: true
    secrets:
      SLACK_BOT_TOKEN:
        required: true



jobs:
  post-slack-msg:
    name: Post msg to Slack
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RUN_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

    steps:
      - name: Post in progress msg on Slack
        if: inputs.status == ''
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: ${{ inputs.slack_channel_id }}
          payload: |
            {
              "attachments": [
                {
                  "color": "dbab09",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "In progress"
                      }
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "${{ inputs.msg }}"
                        }
                    },
                    {
                      "type": "divider"
                    },
                    {
                        "type": "context",
                        "elements": [
                            {
                                "type": "mrkdwn",
                                "text": "status update by ${{ github.actor }} from ${{ github.repository }}."
                            }
                        ]
                    },
                    {
                        "type": "context",
                        "elements": [
                            {
                                  "type": "mrkdwn",
                                  "text": "<${{ env.RUN_URL }}|check logs>  on Github Action"
                            }
                        ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Post success msg to Slack
        if: inputs.status == 'success'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ inputs.slack_channel_id }}
          payload: |
            {
              "attachments": [
                {
                  "color": "28a745",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "Success"
                      }
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "${{ inputs.msg }}"
                        }
                    },
                    {
                      "type": "divider"
                    },
                    {
                        "type": "context",
                        "elements": [
                            {
                                "type": "mrkdwn",
                                "text": "status update by ${{ github.actor }} from ${{ github.repository }}."
                            }
                        ]
                    },
                    {
                        "type": "context",
                        "elements": [
                            {
                                  "type": "mrkdwn",
                                  "text": "<${{ env.RUN_URL }}|check logs>  on Github Action"
                            }
                        ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Post failure msg to Slack
        if: inputs.status == 'failure'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ inputs.slack_channel_id }}
          payload: |
            {
              "attachments": [
                {
                  "color": "bc0d24",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "Failure"
                      }
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "${{ inputs.msg }}"
                        }
                    },
                    {
                      "type": "divider"
                    },
                    {
                        "type": "context",
                        "elements": [
                            {
                                "type": "mrkdwn",
                                "text": "status update by ${{ github.actor }} from ${{ github.repository }}."
                            }
                        ]
                    },
                    {
                        "type": "context",
                        "elements": [
                            {
                                  "type": "mrkdwn",
                                  "text": "<${{ env.RUN_URL }}|check logs>  on Github Action"
                            }
                        ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Post cancelled msg to Slack
        if: inputs.status == 'cancelled'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ inputs.slack_channel_id }}
          payload: |
            {
              "attachments": [
                {
                  "color": "808080",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "Cancelled"
                      }
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "${{ inputs.msg }}"
                        }
                    },
                    {
                      "type": "divider"
                    },
                    {
                        "type": "context",
                        "elements": [
                            {
                                "type": "mrkdwn",
                                "text": "status update by ${{ github.actor }} from ${{ github.repository }}."
                            }
                        ]
                    },
                    {
                        "type": "context",
                        "elements": [
                            {
                                  "type": "mrkdwn",
                                  "text": "<${{ env.RUN_URL }}|check logs>  on Github Action"
                            }
                        ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Post skipped msg to Slack
        if: inputs.status == 'skipped'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ inputs.slack_channel_id }}
          payload: |
            {
              "attachments": [
                {
                  "color": "808080",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "Skipped"
                      }
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "${{ inputs.msg }}"
                        }
                    },
                    {
                      "type": "divider"
                    },
                    {
                        "type": "context",
                        "elements": [
                            {
                                "type": "mrkdwn",
                                "text": "status update by ${{ github.actor }} from ${{ github.repository }}."
                            }
                        ]
                    },
                    {
                        "type": "context",
                        "elements": [
                            {
                                  "type": "mrkdwn",
                                  "text": "<${{ env.RUN_URL }}|check logs>  on Github Action"
                            }
                        ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
