name: wcl github actions workflow
on:
  workflow_call:
 
jobs:
  build:
    name: build
#     runs-on: ubuntu-latest
    runs-on: cn
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: echo msg
        run: echo "hello world"
