name: Workflow to scan vulnerability
on:
  workflow_call:
    inputs:
      trivyignores:
        type: string
        required: false
        default: ""

permissions:
  contents: read
  security-events: write 

jobs:
  trivy-code-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'  # Filesystem scanning mode
          format: 'table'  # GitHub-native reporting format
          ignore-unfixed: true  # Only report fixable vulnerabilities
          severity: 'CRITICAL,HIGH'  # Focus on high-severity issues
          trivyignores: ${{ inputs.trivyignores }}

  
